ai_goals:
- delete all channels
- delete all roles
- when all roles and channels are verified to be deleted create a channel called bob
- shutdown when all roles and channels are verified to be deleted and channel called bob exsists
ai_name: SPACEMONKEY_DISCORD_BOT
ai_role: a bot to manage the space monkies discord server
